# 2.1 — Базовые модели (MLP, GRU, TCN)

**Папка 2 «Обучение моделей», подноутбук 1.** Для каждой базовой модели выполняется
**подбор гиперпараметров перебором по сетке (grid search)** с богатой историей (все метрики
по каждой конфигурации). Метрика отбора выбирается явно. Лучшая комбинация сохраняется в
`models/<имя>/hyperparams.json`, после чего финальное обучение **читает этот JSON** и обучает
модель «начисто» с отслеживанием метрик. Рисунки и таблицы — на английском.

## Окружение и данные

In [1]:
import sys
from pathlib import Path


def find_repo_root(start: Path) -> Path:
    """Найти корень репозитория по наличию pyproject.toml вверх по дереву."""
    start = start.resolve()
    for candidate in [start, *start.parents]:
        if (candidate / "pyproject.toml").exists():
            return candidate
    return start


REPO_ROOT = find_repo_root(Path.cwd())
if str(REPO_ROOT / "src") not in sys.path:
    sys.path.insert(0, str(REPO_ROOT / "src"))

import numpy as np
import pandas as pd
from IPython.display import display

from liquefaction_ai.viz import register_theme

register_theme()

# Если True — все фигуры сохраняются в results/figs (.html и .png)
SAVE_FIGS = True
DATA_DIR = REPO_ROOT / "data" / "demo_run"
MODELS_DIR = REPO_ROOT / "models"

import torch

from liquefaction_ai import load_population_artifact, prepare_benchmark_dataset, train_model
from liquefaction_ai.training import grid_search, write_hyperparams, read_hyperparams, save_trained_model
from liquefaction_ai.evaluation import METRICS, english_metric_table, metrics_catalog, subsample_split
from liquefaction_ai.viz import grid_search_dashboard, training_dashboard, lines

population, config = load_population_artifact(DATA_DIR)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
benchmark = prepare_benchmark_dataset(population, config, device)
static_dim = benchmark["train"]["static"].shape[1]
prefix_dim = benchmark["train"]["prefix_summary"].shape[1]
seq_dim = benchmark["train"]["seq_in"].shape[-1]

# Grid search выполняется на компактной подвыборке (для ранжирования гиперпараметров).
gs_train = subsample_split(benchmark["train"], 2000, config.seed)
gs_val = subsample_split(benchmark["val"], 600, config.seed + 1)


def show_grid_dashboard(res, grid, score, metric_keys, fig_id):
    """Построить дашборд grid search: по Y — метрики, по X — текст конфигурации."""
    info = METRICS[score]
    labels = {k: f"{METRICS[k].name} ({METRICS[k].units})" for k in metric_keys}
    fmts = {k: METRICS[k].fmt for k in metric_keys}
    return grid_search_dashboard(res, metric_keys, list(grid.keys()), score,
                                 metric_labels=labels, metric_fmts=fmts,
                                 lower_is_better=info.lower_is_better, target=info.target,
                                 save=SAVE_FIGS, fig_id=fig_id)

print("device:", device, "| dims static/prefix/seq:", static_dim, prefix_dim, seq_dim)
from liquefaction_ai.models import (GRUBaseline, LSTMBaseline, RiskMLP, TCNBaseline,
                                    TransformerBaseline, FTTransformer, CatBoostBaseline,
                                    PINNBaseline, DeepStateBaseline, RealNVPFlow, NeuralSplineFlow)

device: cpu | dims static/prefix/seq: 34 6 5

## Каталог метрик

Все метрики качества определены с подробными описаниями в `liquefaction_ai.evaluation.metrics`
(`METRICS`) и импортируются в ноутбук. **Метрику отбора лучших гиперпараметров можно выбрать**
через переменную `SELECTION_METRIC` ниже.

In [2]:
display(metrics_catalog())

,Metric,Name,Units,Direction,Description
0,val_loss,Validation loss,–,lower is better,Mean validation value of the model's training ...
1,Traj_RMSE,Trajectory RMSE,–,lower is better,Root-mean-square error of the predicted pore-p...
2,Traj_MAE,Trajectory MAE,–,lower is better,Mean absolute error of the predicted PPR(N) tr...
3,Traj_MSE,Trajectory MSE,–,lower is better,Mean squared error of the predicted PPR(N) tra...
4,N_liq_MAE,MAE of N_liq,cycles,lower is better,Mean absolute error of the predicted number of...
5,AUROC,AUROC,–,higher is better,Area under the ROC curve for liquefaction-risk...
6,AUPRC,AUPRC,–,higher is better,Area under the precision–recall curve; classif...
7,Brier,Brier score,–,lower is better,Mean squared error of the predicted liquefacti...
8,ECE,Expected calibration error,–,lower is better,Average absolute gap between predicted confide...
9,Coverage_90,90% interval coverage,–,target ≈ 0.9,Empirical fraction of true PPR values that fal...
10,Interval_Width_90,90% interval width,–,lower is better,Mean width of the predicted 90% interval for P...
11,N_liq_RMSE,RMSE of N_liq,cycles,lower is better,Root-mean-square error of predicted cycles to ...
12,N_liq_logMAE,log-MAE of N_liq,log-cycles,lower is better,Mean absolute error of N_liq in log1p scale. C...
13,N_liq_logRMSE,log-RMSE of N_liq,log-cycles,lower is better,Root-mean-square error of N_liq in log1p scale...
14,Physics_Violation_Rate,Physics violation rate,–,target ≈ 0.0,Fraction of predictions whose PPR(N) curve is ...
15,Coverage_80,80% interval coverage,–,target ≈ 0.8,Empirical fraction of true PPR values inside t...
16,Coverage_95,95% interval coverage,–,target ≈ 0.95,Empirical fraction of true PPR values inside t...
17,Calibration_Error,Calibration error,–,target ≈ 0.0,Mean absolute gap between empirical and nomina...
18,Traj_NLL,Trajectory NLL,nats,lower is better,Gaussian negative log-likelihood of the observ...
19,Traj_CRPS,Trajectory CRPS,–,lower is better,Continuous ranked probability score of the pre...
20,CRR_RMSE,CRR-curve RMSE,–,lower is better,RMSE between the predicted cyclic-resistance c...

## Шаг 1. Grid search, история по всем метрикам и сохранение гиперпараметров

Для каждой модели задана своя метрика отбора `score` (можно менять). Дашборд показывает
все метрики по каждой конфигурации; лучшая по метрике отбора подсвечена.

In [3]:
base_specs = {
    "mlp_risk": dict(display="MLP-Risk", cls=RiskMLP,
                     fixed=dict(static_dim=static_dim, prefix_dim=prefix_dim),
                     grid={"hidden_dim": [64, 128]}, score="Brier",
                     metrics=["Brier", "ECE", "AUROC", "N_liq_MAE"]),
    "gru": dict(display="GRU", cls=GRUBaseline,
                fixed=dict(static_dim=static_dim, seq_dim=seq_dim),
                grid={"hidden_dim": [64, 96]}, score="Traj_RMSE",
                metrics=["Traj_RMSE", "AUROC", "Brier", "N_liq_MAE"]),
    "tcn": dict(display="TCN", cls=TCNBaseline,
                fixed=dict(static_dim=static_dim, seq_dim=seq_dim),
                grid={"hidden_dim": [64, 96]}, score="Traj_RMSE",
                metrics=["Traj_RMSE", "AUROC", "Brier", "N_liq_MAE"]),
    "lstm": dict(display="LSTM", cls=LSTMBaseline,
                 fixed=dict(static_dim=static_dim, seq_dim=seq_dim),
                 grid={"hidden_dim": [64, 96]}, score="Traj_RMSE",
                 metrics=["Traj_RMSE", "AUROC", "Brier", "N_liq_MAE"]),
    "transformer": dict(display="Transformer", cls=TransformerBaseline,
                 fixed=dict(static_dim=static_dim, seq_dim=seq_dim, seq_len=config.seq_len),
                 grid={"hidden_dim": [64, 96]}, score="Traj_RMSE",
                 metrics=["Traj_RMSE", "AUROC", "Brier", "N_liq_MAE"]),
    "ft_transformer": dict(display="FT-Transformer", cls=FTTransformer,
                 fixed=dict(static_dim=static_dim, prefix_dim=prefix_dim),
                 grid={"n_layers": [2, 3]}, score="Brier",
                 metrics=["Brier", "ECE", "AUROC", "N_liq_MAE"]),
    "pinn": dict(display="PINN", cls=PINNBaseline,
                 fixed=dict(static_dim=static_dim, seq_dim=seq_dim),
                 grid={"hidden_dim": [64, 96]}, score="Traj_RMSE",
                 metrics=["Traj_RMSE", "AUROC", "Brier", "N_liq_MAE"]),
    "deepstate": dict(display="DeepState", cls=DeepStateBaseline,
                 fixed=dict(static_dim=static_dim, seq_dim=seq_dim),
                 grid={"hidden_dim": [64, 96]}, score="Traj_RMSE",
                 metrics=["Traj_RMSE", "AUROC", "Brier", "N_liq_MAE"]),
    "realnvp": dict(display="RealNVP", cls=RealNVPFlow,
                 fixed=dict(static_dim=static_dim, prefix_dim=prefix_dim, seq_len=config.seq_len),
                 grid={"n_layers": [4, 6]}, score="Traj_RMSE",
                 metrics=["Traj_RMSE", "AUROC", "Brier", "N_liq_MAE"]),
    "nsf": dict(display="Neural Spline Flow", cls=NeuralSplineFlow,
                 fixed=dict(static_dim=static_dim, prefix_dim=prefix_dim, seq_len=config.seq_len),
                 grid={"n_layers": [4, 5]}, score="Traj_RMSE",
                 metrics=["Traj_RMSE", "AUROC", "Brier", "N_liq_MAE"]),
}

for name, spec in base_specs.items():
    cls, fixed, grid, score = spec["cls"], spec["fixed"], spec["grid"], spec["score"]
    res, best = grid_search(lambda p, cls=cls, fixed=fixed: cls(**fixed, **p),
                            grid, gs_train, gs_val, config, device, search_epochs=1, score_metric=score)
    write_hyperparams(MODELS_DIR, name, {"model_type": cls.__name__, "display_name": spec["display"],
                      "model_kwargs": {**fixed, **best}, "search": {"grid": grid, "score_metric": score, "best": best}})
    print(f"[{spec['display']}] selection metric = {score} | best = {best}")
    display(english_metric_table(res).round(4))
    show_grid_dashboard(res, grid, score, spec["metrics"], f"2_1_grid_search_{name}").show()

[MLP-Risk] selection metric = Brier | best = {'hidden_dim': 128}

,hidden_dim,val_loss,MAE N_liq (cycles),RMSE N_liq (cycles),log-MAE N_liq,log-RMSE N_liq,AUROC,AUPRC,Brier,ECE,...,Interval width@80%,Coverage@90%,Interval width@90%,Coverage@95%,Interval width@95%,Calibration error,Trajectory NLL,Trajectory CRPS,CRR-curve RMSE,Produces CRR
0,128,0.191,2357.8059,3696.4299,2.2674,2.6695,0.9983,0.9989,0.0344,0.1128,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1,64,0.506,2362.4336,3761.5652,2.5798,2.9778,0.9744,0.9862,0.1442,0.2686,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0

[save_figure] PNG для '2_1_grid_search_mlp_risk' не сохранён (нет движка экспорта):
Image export using the "kaleido" engine requires the Kaleido package,
which can be installed using pip:

    $ pip install --upgrade kaleido

[GRU] selection metric = Traj_RMSE | best = {'hidden_dim': 96}

,hidden_dim,val_loss,MAE N_liq (cycles),RMSE N_liq (cycles),log-MAE N_liq,log-RMSE N_liq,AUROC,AUPRC,Brier,ECE,...,Interval width@80%,Coverage@90%,Interval width@90%,Coverage@95%,Interval width@95%,Calibration error,Trajectory NLL,Trajectory CRPS,CRR-curve RMSE,Produces CRR
0,96,0.0798,2396.9294,3811.0103,3.0043,3.5288,0.9838,0.9896,0.2282,0.3650,...,1.9902,1.0,2.5543,1.0,3.0436,0.1167,0.7423,0.2296,NaN,0.0
1,64,0.1865,2384.7214,3798.8469,2.7060,3.2021,0.9735,0.9842,0.2339,0.3608,...,2.2504,1.0,2.8883,1.0,3.4416,0.1167,0.8501,0.2486,NaN,0.0

[save_figure] PNG для '2_1_grid_search_gru' не сохранён (нет движка экспорта):
Image export using the "kaleido" engine requires the Kaleido package,
which can be installed using pip:

    $ pip install --upgrade kaleido

[TCN] selection metric = Traj_RMSE | best = {'hidden_dim': 64}

,hidden_dim,val_loss,MAE N_liq (cycles),RMSE N_liq (cycles),log-MAE N_liq,log-RMSE N_liq,AUROC,AUPRC,Brier,ECE,...,Interval width@80%,Coverage@90%,Interval width@90%,Coverage@95%,Interval width@95%,Calibration error,Trajectory NLL,Trajectory CRPS,CRR-curve RMSE,Produces CRR
0,64,0.2270,2388.1831,3802.8721,2.7768,3.2828,0.9692,0.9805,0.2427,0.0875,...,2.3206,1.0,2.9784,1.0,3.5489,0.1167,0.8833,0.2570,NaN,0.0
1,96,0.2549,2389.0142,3803.7275,2.7953,3.3039,0.9504,0.9753,0.2440,0.2911,...,2.3898,1.0,3.0673,1.0,3.6548,0.1167,0.9099,0.2629,NaN,0.0

[save_figure] PNG для '2_1_grid_search_tcn' не сохранён (нет движка экспорта):
Image export using the "kaleido" engine requires the Kaleido package,
which can be installed using pip:

    $ pip install --upgrade kaleido

[LSTM] selection metric = Traj_RMSE | best = {'hidden_dim': 64}

,hidden_dim,val_loss,MAE N_liq (cycles),RMSE N_liq (cycles),log-MAE N_liq,log-RMSE N_liq,AUROC,AUPRC,Brier,ECE,...,Interval width@80%,Coverage@90%,Interval width@90%,Coverage@95%,Interval width@95%,Calibration error,Trajectory NLL,Trajectory CRPS,CRR-curve RMSE,Produces CRR
0,64,0.2693,2389.4934,3803.8389,2.8064,3.3102,0.9940,0.9965,0.2437,0.3113,...,2.4432,1.0,3.1358,1.0,3.7365,0.1167,0.9244,0.2629,NaN,0.0
1,96,0.2062,2384.4331,3799.1868,2.6998,3.2022,0.9816,0.9904,0.2457,0.1118,...,2.2652,1.0,2.9073,1.0,3.4642,0.1167,0.8616,0.2526,NaN,0.0

[save_figure] PNG для '2_1_grid_search_lstm' не сохранён (нет движка экспорта):
Image export using the "kaleido" engine requires the Kaleido package,
which can be installed using pip:

    $ pip install --upgrade kaleido

[Transformer] selection metric = Traj_RMSE | best = {'hidden_dim': 64}

,hidden_dim,val_loss,MAE N_liq (cycles),RMSE N_liq (cycles),log-MAE N_liq,log-RMSE N_liq,AUROC,AUPRC,Brier,ECE,...,Interval width@80%,Coverage@90%,Interval width@90%,Coverage@95%,Interval width@95%,Calibration error,Trajectory NLL,Trajectory CRPS,CRR-curve RMSE,Produces CRR
0,64,-0.8398,2371.2498,3780.7678,2.5298,2.9909,0.9927,0.9960,0.1307,0.3084,...,0.6883,0.9635,0.8834,0.9864,1.0527,0.0673,-0.0968,0.1232,NaN,0.0
1,96,-0.4395,2289.7405,3674.7705,1.8820,2.2317,0.9970,0.9982,0.1203,0.2968,...,0.5602,0.7515,0.7189,0.8127,0.8567,0.1408,0.3246,0.1546,NaN,0.0

[save_figure] PNG для '2_1_grid_search_transformer' не сохранён (нет движка экспорта):
Image export using the "kaleido" engine requires the Kaleido package,
which can be installed using pip:

    $ pip install --upgrade kaleido

[FT-Transformer] selection metric = Brier | best = {'n_layers': 2}

,n_layers,val_loss,MAE N_liq (cycles),RMSE N_liq (cycles),log-MAE N_liq,log-RMSE N_liq,AUROC,AUPRC,Brier,ECE,...,Interval width@80%,Coverage@90%,Interval width@90%,Coverage@95%,Interval width@95%,Calibration error,Trajectory NLL,Trajectory CRPS,CRR-curve RMSE,Produces CRR
0,2,0.6775,2366.2126,3448.1973,2.1382,2.4161,0.9991,0.9994,0.2301,0.1339,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1,3,0.7020,2293.2141,3657.5000,1.9717,2.3450,0.9791,0.9855,0.2436,0.1432,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0

[save_figure] PNG для '2_1_grid_search_ft_transformer' не сохранён (нет движка экспорта):
Image export using the "kaleido" engine requires the Kaleido package,
which can be installed using pip:

    $ pip install --upgrade kaleido

[PINN] selection metric = Traj_RMSE | best = {'hidden_dim': 96}

,hidden_dim,val_loss,MAE N_liq (cycles),RMSE N_liq (cycles),log-MAE N_liq,log-RMSE N_liq,AUROC,AUPRC,Brier,ECE,...,Interval width@80%,Coverage@90%,Interval width@90%,Coverage@95%,Interval width@95%,Calibration error,Trajectory NLL,Trajectory CRPS,CRR-curve RMSE,Produces CRR
0,96,-0.4774,2336.1411,3714.2532,2.1762,2.6057,0.9782,0.9877,0.1674,0.3144,...,0.5074,0.7444,0.6513,0.8182,0.7760,0.1375,0.2417,0.1508,NaN,0.0
1,64,-0.4493,2390.5144,3811.3225,2.8817,3.5215,0.9585,0.9764,0.2081,0.3588,...,0.8251,0.9004,1.0589,0.9709,1.2618,0.0104,0.2279,0.1753,NaN,0.0

[save_figure] PNG для '2_1_grid_search_pinn' не сохранён (нет движка экспорта):
Image export using the "kaleido" engine requires the Kaleido package,
which can be installed using pip:

    $ pip install --upgrade kaleido

[DeepState] selection metric = Traj_RMSE | best = {'hidden_dim': 96}

,hidden_dim,val_loss,MAE N_liq (cycles),RMSE N_liq (cycles),log-MAE N_liq,log-RMSE N_liq,AUROC,AUPRC,Brier,ECE,...,Interval width@80%,Coverage@90%,Interval width@90%,Coverage@95%,Interval width@95%,Calibration error,Trajectory NLL,Trajectory CRPS,CRR-curve RMSE,Produces CRR
0,96,0.1817,2387.9360,3802.1682,2.7724,3.2692,0.9368,0.9578,0.2306,0.1351,...,2.1307,1.0,2.7347,1.0,3.2585,0.1167,0.8467,0.2663,NaN,0.0
1,64,0.2261,2388.7607,3803.3701,2.7902,3.2980,0.8380,0.8813,0.2406,0.1291,...,2.2298,1.0,2.8618,1.0,3.4101,0.1167,0.8836,0.2728,NaN,0.0

[save_figure] PNG для '2_1_grid_search_deepstate' не сохранён (нет движка экспорта):
Image export using the "kaleido" engine requires the Kaleido package,
which can be installed using pip:

    $ pip install --upgrade kaleido

[RealNVP] selection metric = Traj_RMSE | best = {'n_layers': 6}

,n_layers,val_loss,MAE N_liq (cycles),RMSE N_liq (cycles),log-MAE N_liq,log-RMSE N_liq,AUROC,AUPRC,Brier,ECE,...,Interval width@80%,Coverage@90%,Interval width@90%,Coverage@95%,Interval width@95%,Calibration error,Trajectory NLL,Trajectory CRPS,CRR-curve RMSE,Produces CRR
0,6,4.2481,2389.9060,3804.7358,2.8177,3.3388,0.6209,0.7431,0.2405,0.0726,...,0.5405,0.5876,0.6937,0.7032,0.8266,0.2926,0.6566,0.2068,NaN,0.0
1,4,5.5865,2386.2668,3799.7227,2.7388,3.2234,0.5184,0.6484,0.2547,0.1253,...,0.5320,0.5744,0.6828,0.6853,0.8136,0.3069,0.6796,0.2080,NaN,0.0

[save_figure] PNG для '2_1_grid_search_realnvp' не сохранён (нет движка экспорта):
Image export using the "kaleido" engine requires the Kaleido package,
which can be installed using pip:

    $ pip install --upgrade kaleido

[Neural Spline Flow] selection metric = Traj_RMSE | best = {'n_layers': 5}

,n_layers,val_loss,MAE N_liq (cycles),RMSE N_liq (cycles),log-MAE N_liq,log-RMSE N_liq,AUROC,AUPRC,Brier,ECE,...,Interval width@80%,Coverage@90%,Interval width@90%,Coverage@95%,Interval width@95%,Calibration error,Trajectory NLL,Trajectory CRPS,CRR-curve RMSE,Produces CRR
0,5,12.2524,2388.5090,3804.1150,2.7862,3.3074,0.9385,0.9604,0.2220,0.3456,...,0.5370,0.5931,0.6892,0.7174,0.8212,0.2862,0.5940,0.2015,NaN,0.0
1,4,12.2458,2391.5283,3805.3669,2.8630,3.3738,0.9004,0.9441,0.2296,0.2819,...,0.5412,0.5908,0.6946,0.7139,0.8276,0.2860,0.6022,0.2028,NaN,0.0

[save_figure] PNG для '2_1_grid_search_nsf' не сохранён (нет движка экспорта):
Image export using the "kaleido" engine requires the Kaleido package,
which can be installed using pip:

    $ pip install --upgrade kaleido

## Шаг 2. Финальное обучение по сохранённым гиперпараметрам

In [4]:
# Реестр классов всех baseline (имя класса -> класс) и число эпох по семействам
CLS = {RiskMLP.__name__: RiskMLP, GRUBaseline.__name__: GRUBaseline, TCNBaseline.__name__: TCNBaseline,
       LSTMBaseline.__name__: LSTMBaseline, TransformerBaseline.__name__: TransformerBaseline,
       FTTransformer.__name__: FTTransformer, PINNBaseline.__name__: PINNBaseline,
       DeepStateBaseline.__name__: DeepStateBaseline, RealNVPFlow.__name__: RealNVPFlow,
       NeuralSplineFlow.__name__: NeuralSplineFlow}
# PINN — физически-структурированная (больше эпох); остальные baseline — config.baseline_epochs
epoch_map = {name: (config.physics_epochs if name == "pinn" else config.baseline_epochs) for name in base_specs}
histories = {}
for name in base_specs:
    hp = read_hyperparams(MODELS_DIR, name)
    model = CLS[hp["model_type"]](**hp["model_kwargs"]).to(device)
    epochs = epoch_map[name]
    model, history = train_model(model, benchmark["train"], benchmark["val"], epochs=epochs,
                                 model_name=hp["display_name"], config=config, device=device, track_metrics=True)
    save_trained_model(model, MODELS_DIR, name, {**hp, "epochs": epochs, "learning_rate": config.learning_rate,
                       "weight_decay": config.weight_decay, "batch_size": config.batch_size, "seed": config.seed}, history)
    histories[hp["display_name"]] = history
    print("saved:", MODELS_DIR / name)

[MLP-Risk] эпоха 01 | обучение=0.7490 | валидация=0.2463 | val_AUROC=0.997

[MLP-Risk] эпоха 02 | обучение=0.2039 | валидация=0.1169 | val_AUROC=0.999

[MLP-Risk] эпоха 03 | обучение=0.1005 | валидация=0.0731 | val_AUROC=0.999

[MLP-Risk] эпоха 04 | обучение=0.0682 | валидация=0.0495 | val_AUROC=0.999

saved: /sessions/determined-cool-fermat/mnt/liquefaction-ai/models/mlp_risk

[GRU] эпоха 01 | обучение=0.2373 | валидация=0.0437 | val_AUROC=0.991 | val_RMSE=0.3304

[GRU] эпоха 02 | обучение=-0.0295 | валидация=-0.3324 | val_AUROC=0.989 | val_RMSE=0.3109

[GRU] эпоха 03 | обучение=-0.4165 | валидация=-0.6009 | val_AUROC=0.991 | val_RMSE=0.2624

[GRU] эпоха 04 | обучение=-0.5873 | валидация=-0.3866 | val_AUROC=0.991 | val_RMSE=0.2554

saved: /sessions/determined-cool-fermat/mnt/liquefaction-ai/models/gru

[TCN] эпоха 01 | обучение=0.3251 | валидация=0.2888 | val_AUROC=0.845 | val_RMSE=0.3347

[TCN] эпоха 02 | обучение=0.2791 | валидация=0.2193 | val_AUROC=0.870 | val_RMSE=0.3323

[TCN] эпоха 03 | обучение=0.1847 | валидация=0.0169 | val_AUROC=0.679 | val_RMSE=0.3275

[TCN] эпоха 04 | обучение=0.0066 | валидация=-0.2471 | val_AUROC=0.509 | val_RMSE=0.3055

saved: /sessions/determined-cool-fermat/mnt/liquefaction-ai/models/tcn

[LSTM] эпоха 01 | обучение=0.3009 | валидация=0.2519 | val_AUROC=0.949 | val_RMSE=0.3151

[LSTM] эпоха 02 | обучение=0.2373 | валидация=0.1678 | val_AUROC=0.970 | val_RMSE=0.3073

[LSTM] эпоха 03 | обучение=0.1379 | валидация=0.0069 | val_AUROC=0.968 | val_RMSE=0.2934

[LSTM] эпоха 04 | обучение=-0.0584 | валидация=-0.2917 | val_AUROC=0.972 | val_RMSE=0.2735

saved: /sessions/determined-cool-fermat/mnt/liquefaction-ai/models/lstm

[Transformer] эпоха 01 | обучение=0.1175 | валидация=-0.6472 | val_AUROC=0.991 | val_RMSE=0.2486

[Transformer] эпоха 02 | обучение=-0.7512 | валидация=-1.0699 | val_AUROC=0.997 | val_RMSE=0.1816

[Transformer] эпоха 03 | обучение=-1.1208 | валидация=-1.3656 | val_AUROC=0.999 | val_RMSE=0.1310

[Transformer] эпоха 04 | обучение=-1.3418 | валидация=-1.5088 | val_AUROC=0.998 | val_RMSE=0.1096

saved: /sessions/determined-cool-fermat/mnt/liquefaction-ai/models/transformer

[FT-Transformer] эпоха 01 | обучение=0.9680 | валидация=0.7509 | val_AUROC=0.996

[FT-Transformer] эпоха 02 | обучение=0.7120 | валидация=0.6364 | val_AUROC=0.997

[FT-Transformer] эпоха 03 | обучение=0.6072 | валидация=0.4785 | val_AUROC=0.997

[FT-Transformer] эпоха 04 | обучение=0.4180 | валидация=0.2236 | val_AUROC=0.998

saved: /sessions/determined-cool-fermat/mnt/liquefaction-ai/models/ft_transformer
[PINN] эпоха 01 | обучение=-0.1495 | валидация=-0.5598 | val_AUROC=0.985 | val_RMSE=0.2237

[PINN] эпоха 02 | обучение=-0.8177 | валидация=-1.2825 | val_AUROC=0.986 | val_RMSE=0.1382

[PINN] эпоха 03 | обучение=-1.1446 | валидация=-1.3031 | val_AUROC=0.990 | val_RMSE=0.1443

[PINN] эпоха 04 | обучение=-1.3370 | валидация=-1.5587 | val_AUROC=0.990 | val_RMSE=0.0980

[PINN] эпоха 05 | обучение=-1.5190 | валидация=-1.6473 | val_AUROC=0.991 | val_RMSE=0.1077

[PINN] эпоха 06 | обучение=-1.5968 | валидация=-1.7739 | val_AUROC=0.991 | val_RMSE=0.0983

saved: /sessions/determined-cool-fermat/mnt/liquefaction-ai/models/pinn

[DeepState] эпоха 01 | обучение=0.2906 | валидация=0.1728 | val_AUROC=0.974 | val_RMSE=0.3988

[DeepState] эпоха 02 | обучение=0.0958 | валидация=-0.0797 | val_AUROC=0.984 | val_RMSE=0.3965

[DeepState] эпоха 03 | обучение=-0.1868 | валидация=-0.2157 | val_AUROC=0.987 | val_RMSE=0.3926

[DeepState] эпоха 04 | обучение=-0.3524 | валидация=-0.3961 | val_AUROC=0.988 | val_RMSE=0.3874

saved: /sessions/determined-cool-fermat/mnt/liquefaction-ai/models/deepstate
[RealNVP] эпоха 01 | обучение=14.9711 | валидация=4.8316 | val_AUROC=0.759 | val_RMSE=0.3322

[RealNVP] эпоха 02 | обучение=4.3198 | валидация=2.8793 | val_AUROC=0.925 | val_RMSE=0.3278

[RealNVP] эпоха 03 | обучение=2.7641 | валидация=2.3482 | val_AUROC=0.980 | val_RMSE=0.3224

[RealNVP] эпоха 04 | обучение=2.3344 | валидация=2.1525 | val_AUROC=0.989 | val_RMSE=0.3074

saved: /sessions/determined-cool-fermat/mnt/liquefaction-ai/models/realnvp

[Neural Spline Flow] эпоха 01 | обучение=12.9750 | валидация=12.2045 | val_AUROC=0.954 | val_RMSE=0.3259

[Neural Spline Flow] эпоха 02 | обучение=12.4539 | валидация=11.9471 | val_AUROC=0.978 | val_RMSE=0.3114

[Neural Spline Flow] эпоха 03 | обучение=12.2824 | валидация=11.7869 | val_AUROC=0.982 | val_RMSE=0.2985

[Neural Spline Flow] эпоха 04 | обучение=12.1154 | валидация=11.6532 | val_AUROC=0.986 | val_RMSE=0.2873

saved: /sessions/determined-cool-fermat/mnt/liquefaction-ai/models/nsf

## Кривые обучения с метриками

In [5]:
palette = ["#0b6efd", "#198754", "#fd7e14", "#6610f2", "#d63384", "#20c997", "#dc3545", "#0dcaf0", "#ffc107", "#6f42c1"]
colors = {disp: palette[i % len(palette)] for i, disp in enumerate(histories)}
for disp, hist in histories.items():
    training_dashboard(hist, title=f"Training dynamics — {disp}", model_color=colors[disp],
                       save=SAVE_FIGS, fig_id=f"2_1_training_{disp.lower().replace('-', '_')}").show()

[save_figure] PNG для '2_1_training_mlp_risk' не сохранён (нет движка экспорта):
Image export using the "kaleido" engine requires the Kaleido package,
which can be installed using pip:

    $ pip install --upgrade kaleido

[save_figure] PNG для '2_1_training_gru' не сохранён (нет движка экспорта):
Image export using the "kaleido" engine requires the Kaleido package,
which can be installed using pip:

    $ pip install --upgrade kaleido

[save_figure] PNG для '2_1_training_tcn' не сохранён (нет движка экспорта):
Image export using the "kaleido" engine requires the Kaleido package,
which can be installed using pip:

    $ pip install --upgrade kaleido

[save_figure] PNG для '2_1_training_lstm' не сохранён (нет движка экспорта):
Image export using the "kaleido" engine requires the Kaleido package,
which can be installed using pip:

    $ pip install --upgrade kaleido

[save_figure] PNG для '2_1_training_transformer' не сохранён (нет движка экспорта):
Image export using the "kaleido" engine requires the Kaleido package,
which can be installed using pip:

    $ pip install --upgrade kaleido

[save_figure] PNG для '2_1_training_ft_transformer' не сохранён (нет движка экспорта):
Image export using the "kaleido" engine requires the Kaleido package,
which can be installed using pip:

    $ pip install --upgrade kaleido

[save_figure] PNG для '2_1_training_pinn' не сохранён (нет движка экспорта):
Image export using the "kaleido" engine requires the Kaleido package,
which can be installed using pip:

    $ pip install --upgrade kaleido

[save_figure] PNG для '2_1_training_deepstate' не сохранён (нет движка экспорта):
Image export using the "kaleido" engine requires the Kaleido package,
which can be installed using pip:

    $ pip install --upgrade kaleido

[save_figure] PNG для '2_1_training_realnvp' не сохранён (нет движка экспорта):
Image export using the "kaleido" engine requires the Kaleido package,
which can be installed using pip:

    $ pip install --upgrade kaleido

[save_figure] PNG для '2_1_training_neural spline flow' не сохранён (нет движка экспорта):
Image export using the "kaleido" engine requires the Kaleido package,
which can be installed using pip:

    $ pip install --upgrade kaleido

## Итог

Базовые модели подобраны grid search (с выбором метрики) и обучены. Дальше — **2.2 DPI-Flow**.

In [6]:
# --- CatBoost (табличный градиентный бустинг) ---
# Не нейросеть, поэтому обучается своим .fit (не train_model) и сохраняется нативно.
cb = CatBoostBaseline(static_dim, prefix_dim).fit(benchmark["train"], benchmark["val"])
cb.save(MODELS_DIR, "catboost")
write_hyperparams(MODELS_DIR, "catboost", {"model_type": "CatBoostBaseline", "display_name": "CatBoost",
                  "model_kwargs": dict(static_dim=static_dim, prefix_dim=prefix_dim)})
print("saved:", MODELS_DIR / "catboost")

saved: /sessions/determined-cool-fermat/mnt/liquefaction-ai/models/catboost